name: flutter_web
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  responsive_framework: ^0.2.0
  flutter_svg: ^2.0.0+1
  percent_indicator: ^4.2.2
  intl: ^0.18.0
  eva_icons_flutter: ^3.1.0
  flutter_staggered_grid_view: ^0.4.1

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

